### ISSUE TITLE
Change entry status from AI-generated to Curated

### ISSUE THREAD

**Issue by typhainepl** [ProteinsWebTeam/pronto#103]
At the moment, when an entry is _AI-generated_, to change its status to _Curated_ we have to first check 'Reviewed>Update' then 'Curated>Update'. It would be nice if we could directly change from _AI-generated_ to _Curated_.

**Comment by matthiasblum** [comment]
Have you tried to directly tick the _Curated: this entry and its annotations will be marked as curated_ checkbox? 
Does an error occur when trying this? If so, for which entry?
It should be possible to directly mark an unreviewed AI-generated entry as curated.

**Comment by typhainepl** [comment]
Yes, that's the checkbox I am referring to.
I tried and couldn't replicate the issue today, but it occurred multiple times for me and the curators during the PANTHER update checking.

**Comment by matthiasblum** [comment]
Feel free to reopen if the issue arises again.
