### ISSUE TITLE
New sanity check

### ISSUE THREAD

**Issue by blazaropinto** [ProteinsWebTeam/pronto#104]
Could the cases below be highlighted in the sanity checks?

1. entry_type='D' and entry_name includes the word 'Family' or 'family'
2. entry_type='F' and entry_name includes the word 'Domain' or 'domain'

**Comment by matthiasblum** [comment]
It is possible, but a significant number of entries (> 1,000) will be highlighted. Here are then randomly picked ones:

| ENTRY\_AC | ENTRY\_TYPE | NAME |
| :--- | :--- | :--- |
| IPR021901 | D | CAS family, C-terminal |
| IPR039350 | F | Prospero homeodomain family |
| IPR026134 | F | MyoD family inhibitor/MyoD family inhibitor domain-containing protein |
| IPR052432 | F | Phosphatidylinositol transfer protein/CRAL-TRIO domain |
| IPR031697 | F | Transmembrane and coiled-coil domain-containing protein 2 |
| IPR032701 | D | Prokaryotic E2 family B domain |
| IPR052670 | F | UPF0654 domain-containing protein |
| IPR038830 | F | Coiled-coil domain-containing protein 186 |
| IPR040275 | F | F-box domain containing protein At5g39450-like |
| IPR009170 | F | PR domain zinc finger protein 2 |

Let me know if you want to go ahead with this change.

**Comment by blazaropinto** [comment]
maybe just with

1.     entry_type='D' and entry_name includes the word 'Family'
2.     entry_type='F' and entry_name includes the word 'Domain'

and ignoring AI-generated entries ..
it's more manageable at the beginning? (I'm assuming we'd need to add a lot of exceptions in the first round, but yes, more than 1000 is a very big number to do manually)

**Comment by blazaropinto** [comment]
These kind of examples are exactly the ones I want highlighted (actually the ones above would need checking -that can be unnecessarily confusing for InterPro users - I'll raise this in the Curation meeting later to do it way before the next freeze, where that list should be small). But yes, this seems to be the sanity checks required.
