### ISSUE TITLE
Greek letters

### ISSUE THREAD

**Issue by blazaropinto** [ProteinsWebTeam/pronto#62]
I just found `...beta-α-β topology` [here](http://www.ebi.ac.uk/interpro/entry/InterPro/IPR011649/) and remembered we talked about solving this cases last year, just dropping it here so we don't forget about it

I searched for the examples and comments I wrote by then:

Specific expressions we found while updating annotations:

- `alpha-helice` was automatically changed but `alpha helice` wasn’t (same for everything like that, without hyphen)

- expressions like `alpha/beta/alpha`, `alpha+beta`, `all-alpha` , `alpha/beta-barrel` , `alpha/beta(2)/alpha/beta` weren’t changed

- other cases (as the first I mentioned) are changed just partially, which looks weird

I don’t know if sanity checks can help avoid things like that are missed? (otherwise we could just look for these.. make lists?)

**Comment by typhainepl** [comment]
I have replaced the partially changed greek characters and generated a more exhaustive [list of potential characters to change](https://docs.google.com/spreadsheets/d/1ZW9h-Qa-rU3wX0cAEW1cyRiWHnA9VvxQ0vxp--zm_K8/edit?usp=sharing).
