### ISSUE TITLE
old tags/labels that don't convert to links

### ISSUE THREAD

**Issue by blazaropinto** [ProteinsWebTeam/pronto#65]
example:
[tigrfams:TIGR03793] in http://www.ebi.ac.uk/interpro/entry/InterPro/IPR022514/

I'm changing this to the corresponding [interpro:IPRxxxxxx] as I find them in old entries while working on the NCBIfam update, but I'm sure some cases will be missed in this way... (I see this converts to a link in the public site but not in Pronto)
![image](https://user-images.githubusercontent.com/79019608/228554818-ef7bfb75-3285-4aaa-8432-4c878f20a549.png)

**Comment by matthiasblum** [comment]
External TIGRFams/NCBIfam references were updated (`[TIGRFams:...]` to `[ncbifam:...]`).
