### ISSUE TITLE
standardisation of words/expressions in CABs (e.g. alphaproteobacteria, α-Proteobacteria....)

### ISSUE THREAD

**Issue by blazaropinto** [ProteinsWebTeam/pronto#66]
I thought of this reviewing examples of expressions with greek letters in CABs:
there are certain things like alphaproteobacteria that are written in a lot of different ways (due to inconsistency in scientific literature), but maybe we should standardise this expressions in the CABs in InterPro to be consistent so more clear?

**Comment by matthiasblum** [comment]
You can use the "Misspellings" sanity checks. If you add the terms you don't want to see anymore (e.g. `alpha-proteobacteria` and `alphaproteobacteria`), they will be picked up during sanity checks.

**Comment by blazaropinto** [comment]
Sure, we will discuss about what terms have this issue and the form we want to use normally for them and then do that :)
