### ISSUE TITLE
Bind variables security issue

### ISSUE THREAD

**Issue by typhainepl** [ProteinsWebTeam/pronto#69]
The following files have security issues in SQL requests:

- database.py line 226:

> cur.execute(
>             f"""
>             SELECT accession, counts
>             FROM webfront_entry
>             WHERE accession IN ({','.join('%s' for _ in accessions)})
>             """,
>             accessions,
>         )

- databases.py line 38: 

> cur.execute(
>         f"""
>         SELECT id, name, name_long, version, updated
>         FROM interpro.database
>         WHERE id IN ({','.join(['%s' for _ in num_signatures])})
>         """,
>         list(num_signatures.keys())
>     )

- proteome.py line 292:

> cur.execute(
>             F"""
>             SELECT id, name
>             FROM interpro.proteome
>             WHERE id IN ({','.join(['%s' for _ in params])})
>             """,
>             params
>         )

- signatures/descriptions.py line 16:

> cur.execute(
>             f"""
>             SELECT p.name_id, pn.text, p.signature_acc, p.cnt
>             FROM (
>                 SELECT name_id, signature_acc, COUNT(*) cnt
>                 FROM signature2protein
>                 WHERE signature_acc IN ({','.join("%s" for _ in accessions)})
>                 {'AND is_reviewed' if reviewed_only else ''}
>                 GROUP BY name_id, signature_acc
>             ) p
>             INNER JOIN protein_name pn ON p.name_id = pn.name_id
>             """, accessions
>         )

- signatures/comments.py line 15:

> cur.execute(
>             f"""
>             SELECT ps.comment_id, min(ps.comment_text), 
>                    sp.signature_acc, COUNT(*) cnt
>             FROM signature2protein sp
>             INNER JOIN protein_similarity ps ON sp.protein_acc = ps.protein_acc
>             WHERE sp.signature_acc IN ({','.join("%s" for _ in accessions)})
>             GROUP BY ps.comment_id, signature_acc
>             """, accessions
>         )

- signatures/taxonomy.py line 58:

> cur.execute(
>         f"""
>         SELECT t.id, t.name, p.signature_acc, p.cnt 
>         FROM (
>             SELECT sp.signature_acc, l.parent_id, COUNT(*) cnt
>             FROM signature2protein sp
>             INNER JOIN taxon t
>               ON sp.taxon_left_num = t.left_number
>             INNER JOIN lineage l
>               ON t.id = l.child_id AND l.parent_rank = %s
>             WHERE sp.signature_acc IN ({','.join('%s' for _ in accessions)})
>             {taxon_cond}
>             GROUP BY sp.signature_acc, l.parent_id
>         ) p
>         INNER JOIN taxon t
>           ON p.parent_id = t.id
>         """, params
>     )

- signatures/taxonomy.py line 126:

> cur.execute(
>         f"""
>         SELECT t2.id, MIN(t2.name), MIN(t2.rank), sp.signature_acc, COUNT(*)
>         FROM signature2protein sp
>         INNER JOIN taxon t
>           ON sp.taxon_left_num = t.left_number
>         INNER JOIN lineage l
>           ON t.id = l.child_id AND l.parent_id = %s
>         INNER JOIN taxon t2 
>           ON l.parent_id = t2.parent_id 
>           AND t.left_number BETWEEN t2.left_number AND t2.right_number
>         WHERE sp.signature_acc IN ({','.join('%s' for _ in accessions)})
>         GROUP BY sp.signature_acc, t2.id;
>         """, tuple([taxon_id] + accessions)

**Comment by matthiasblum** [comment]
These are not security issues. 

With Psycopg, the library to query PostgreSQL databases, variable binding is done using `%s` as placeholder (like `:1`, `:2`, etc. with cx_Oracle). Documentation: https://www.psycopg.org/docs/usage.html#passing-parameters-to-sql-queries.

This is different from the old string formatting using the percent sign `%`:

```py
name = "stranger"
print("Hello %s" % name)
# Hello stranger
```

**Comment by typhainepl** [comment]
But that's what I was doing in the code below:

> pg_cur.execute(
        f"""
            SELECT t.id, t.name, t.category
            FROM term t
            WHERE t.id IN ({','.join('%s' for _ in term_set)})
            """, term_set
        )

and you changed it for:

> binds = ["%s" for _ in term_ids]
    pg_cur.execute(
        f"""
        SELECT t.id, t.name, t.category
        FROM term t
        WHERE t.id IN ({','.join(binds)})
        """,
        term_ids
    )

**Comment by matthiasblum** [comment]
Hmm, indeed. For https://github.com/ProteinsWebTeam/pronto/pull/59#discussion_r1211984870, you were already using bind variables. No idea why I thought you weren't. :man_facepalming:
