### ISSUE TITLE
Pfam alignment view in Pronto

### ISSUE THREAD

**Issue by tony787** [ProteinsWebTeam/pronto#76]
Pronto is a great tool. It will be very useful to add a possibility to see the Pfam alignment (SEED and FULL) in a similar way as on the InterPro website.

**Comment by matthiasblum** [comment]
Not going to happen. 

Pfam alignments are already available in the InterPro website. And in general, web-based MSA viewers aren't so great, especially when dealing with large data sets. Belvu or Jalview do a much better job.

**Comment by tony787** [comment]
The Pfam alignments available at InterPro site are the public version, Pronto displays data related to the next/future release that as far as I can see can have significant changes not visible on the InterPro site. Jalview has a problem with Xquartz so doesn't run on codon. Jalview however has e web-based version https://www.jalview.org/jalview-js/ . On another note, the SEED alignments are never that big and this one is the one that could be useful.
