### ISSUE TITLE
Avoid missing wrong links to wrong InterPro entries

### ISSUE THREAD

**Issue by blazaropinto** [ProteinsWebTeam/pronto#94]
I found this CAB (AB07392, http://pronto.ebi.ac.uk:5000/entry/IPR011519/) had a link to the wrong InterPro entry and corrected it. The error seemed to be that the link was pointing to the old IP entry where the Pfam:PF01839 used to be integrated (now it is corrected).

Maybe we could have a warning in Pronto when we unintegrate/integrate any signature from an InterPro entry linked to any CAB, so we can quickly check if there is any other change to do.

**Comment by matthiasblum** [comment]
Fixed with 8391ace.
